import { StyleSheet } from "react-native";

const ProfileStyle = StyleSheet.create({
  container: {
    backgroundColor: '#FFFFFF',
    color: '#171B2E',
    flex: 1,
    paddingTop: 28,
    paddingHorizontal: 20,
  },
  headingview: {
    height: 42,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  heading: {
    color: '#171B2E',
    marginRight: 20,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 19,
    fontFamily: 'Poppins-Bold',
  },
  logoutview: {
    height: 42,
    width: 89,
    backgroundColor: '#6F3DE9',
    borderRadius: 28,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  logout: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 19,
    fontFamily: 'Poppins-Bold',
  },
  imgview: {
    height: 125,
    width: 125,
    marginTop: 37,
    borderColor: '#171B2E',
    borderWidth: 1,
    borderStyle: 'dashed',
    backgroundColor: '#E2E2E2',
    borderRadius: 71,
    position: 'relative',
    marginBottom: 31,
  },
  editimg: {
    position: 'absolute',
    height: 16,
    width: 16,
    bottom: 15,
    right: 6,
  },
  inputview: {
    height: 82,
    flexDirection: 'column',
    gap: 12,
    marginBottom: 18,
  },
  input: {
    height: 52,
    color: '#171B2E',
    borderRadius: 26,
    backgroundColor: '#F9F9F9',
    paddingLeft: 16,
    fontFamily: 'Poppins-Regular',
  },
  nametext: {
    color: '#171B2E',
    height: 18,
    marginBottom: 5,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18.2,
    fontFamily: 'Poppins-Bold',
  },
  botton: {
    height: 52,
    borderRadius: 28,
    backgroundColor: '#6F3DE9',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 97,
  },
  botton2: {
    height: 52,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#6F3DE9',
  },
  bottontext: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Poppins-Bold',
  },
  loaderContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Background ko blur karne ke liye
  },
});


export default ProfileStyle;